### ISSUE TITLE
varying number of labeled target samples per class

### ISSUE THREAD

**Issue by zhaoxin94** [TKKim93/APE#2]
Hi, your work is really interesting and impressive. Thank you for make your code open source!

In the Analysis section and supplementary material, you also did some experiments on 5(10, 15, 20)-shot settings. Do you mind to share your split (the txt file) on 5, 10, 15, 20 shot settings?  It will help me a lot to reproduce your results on these  settings.

**Comment by TKKim93** [comment]
Thank you for visiting my repository!

I update the DomainNet splits for additional n-shot settings in the readme.

I wish it would help.

**Comment by meghbhalerao** [comment]
Hi @TKKim93,
Thanks a lot for providing the lists for the 5,10,15 and 20 shot settings! Really appreciate it! I had a small question regarding it. Are you doing the validation with 3 examples per class, even with the 5,10,15 and 20 shot settings?
Thanks,
Megh

**Comment by TKKim93** [comment]
Yes, I used the same split across all the n-shot setting experiments since it also do so in the few-shot learning area.

You can check this at lines 30-33 in utils/return_dataset.py.

**Comment by meghbhalerao** [comment]
Thanks for letting me know, I saw the lines!

**Comment by zhaoxin94** [comment]
@TKKim93  Thanks a lot!
